### ISSUE TITLE
Installation in a new conda environment has missing dependencies

### ISSUE THREAD

**Issue by johanneswerner** [LongTailBio/pangea-django#57]
```bash
conda create -n pangea python=3
conda activate pangea
pip install pangea-api
pangea-api --help
```

complains about missing packages. The following conda packages are missing: 

- `requests`
- `click`
- `pandas`

**Comment by dcdanko** [comment]
Fixed https://github.com/LongTailBio/pangea-django/commit/a92c60af848d0835d330da1a5f7f51ae10a443f3
